name = 'homepage'
main = "app.js"
compatibility_date = "2025-11-04"
keep_vars = true
workers_dev = false

[[routes]]
pattern = "x8m2k5.hmhi.top"
custom_domain = true

[[kv_namespaces]]
binding = "KV"
id = "09bc1aff30474da3ac91e1b90a396759"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
